### ISSUE TITLE
[Spike] Granular roles

### ISSUE THREAD

**Issue by lucasia** [credbull/credbull-defi#12]
Check on more Granular roles in the contracts

- [ ] https://github.com/gnosis/zodiac-modifier-roles

**Comment by pasviegas** [comment]
I was able to spike using the zodiac-modifier-roles. Few pointers:
- there are 2 versions the latest one and the v1. The v1 is audited but uses gnosis/zodiac 3.2.0 which is old.
- the latest one uses openzeppelin 4.8.1 instead of 5.0.0
- The latest one has a compilation at https://github.com/gnosis/zodiac-modifier-roles/blob/main/packages/evm/contracts/Periphery.sol#L12. For my test I just patched the file.

I haven't committed the spike as I want to discuss if which version we should use or if we should be looking at something else. The code is quite complex so reusing the existing module is almost a must.
