### ISSUE TITLE
CredbullSDK dependency breaks vercel build

### ISSUE THREAD

**Issue by lucasia** [credbull/credbull-defi#68]
The vercel build fails due to a CredbullSDK failure.  I've commented this out for now to get the build passing.

If we need to LinkWallet in the App via the SDK, this will fail.

https://github.com/credbull/credbull-defi/blob/e4c79ee994c6a04aa0bcbb0ed35dbc47f842b1e6/packages/app/src/app/(protected)/dashboard/debug/debug-new.tsx#L362-L381

**Comment by jplodge-pro** [comment]
There was a flaw with the `sdk` build that Krishna encountered when he built `main` locally. This could account for this problem, as the issue was where `sdk` put the compliled `.js` and `.d.ts` files. So, downstream dependencies would not resolve the code correctly. This issue has now been fixed, so we will monitor this bug.

**Comment by jplodge-pro** [comment]
The `ci-dev-app.yaml` GitHub Action build has been fixed***** with PR https://github.com/credbull/credbull-defi/pull/76 and some extra work from @lucasia 

***** There is a hack involved.
